name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: 'Create env file'
      run: |
          touch .env
          echo DATABASE_USER_TEST=uroot >> .env
          echo DATABASE_PASSWORD_TEST=proot >> .env
          echo DATABASE_HOST_TEST=localhost >> .env
          echo DATABASE_PORT_TEST=3306 >> .env
          echo DATABASE_NAME_TEST=docs >> .env
          cat .env
          ls
          
    - name: 'Setup mysql'
      run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE docs;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
