name: Go

on:
  push:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-20.04
      
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Create env file'
      run: |
          touch .env
          echo DATABASE_USER_TEST=root >> .env
          echo DATABASE_PASSWORD_TEST=root >> .env
          echo DATABASE_HOST_TEST=127.0.0.1 >> .env
          echo DATABASE_PORT_TEST=3306 >> .env
          echo DATABASE_NAME_TEST=docs >> .env
          cat .env
          ls -a
          
    - name: 'Setup mysql'
      run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE docs;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
          mysql -e 'USE docs; CREATE TABLE docs (id INT PRIMARY KEY AUTO_INCREMENT,title TEXT NOT NULL,body TEXT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());' -uroot -proot
          mysql -V
    
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
